### ISSUE TITLE
Instalação Transparência - PGFN - CEIS - CNEP - CEAF - LENIÊNCIA - DESPESAS - PEP

### ISSUE THREAD

**Issue by kavicosta** [rictom/rede-cnpj#14]
Gostaria de saber como é possível realizar a instalação das demais fontes de dados?

- Doações e Pagamentos - Eleições 2022

https://dadosabertos.tse.jus.br/dataset/dadosabertos-tse-jus-br-dataset-prestacao-de-contas-eleitorais-2022

- Portal da Transparência da CGU

https://www.portaltransparencia.gov.br/download-de-dados/pep
https://www.portaltransparencia.gov.br/download-de-dados/ceaf
https://www.portaltransparencia.gov.br/download-de-dados/ceis
https://www.portaltransparencia.gov.br/download-de-dados/cnep
https://www.portaltransparencia.gov.br/download-de-dados/acordos-leniencia
https://portaldatransparencia.gov.br/download-de-dados/despesas-favorecidos

- Devedores PGFN

https://www.gov.br/pgfn/pt-br/assuntos/divida-ativa-da-uniao/transparencia-fiscal-1/copy_of_dados-abertos

- Pagamentos de municípios no Estado de São Paulo

https://transparencia.tce.sp.gov.br/conjunto-de-dados

**Comment by rictom** [comment]
Olá @kavicosta,

Essa é uma parte que dá bastante trabalho...
A tabela de doações e pagamentos do TSE vc tem que consolidar os dados para gerar algo como  

comentado em https://github.com/rictom/rede-cnpj/issues/4

e carregar na tabela links.db.

As outras tabelas, que viram marcadores (bandeiras) nos itens, devem gerar uma tabela do tipo
de base_dados_modelo.db
![image](https://github.com/rictom/rede-cnpj/assets/71139693/99f95c16-d856-4159-a0f1-895ebc237339)

onde cada registro é algo como
![image](https://github.com/rictom/rede-cnpj/assets/71139693/699e7b6d-7bc2-4ab6-85f0-e7cca86cca20)

e depois no rede.ini vc configura a linha
base_local = base_dados.db (nome do arquivo)
Então tem que fazer um tratamento em cada tabela de pep, ceaf, ceis, etc, colocar nesse formato para funcionar.

**Comment by rictom** [comment]
Fechando o tópico, acho que já deve ter sido resolvido.
