### ISSUE TITLE
Erro  http 500 - Internal server error

### ISSUE THREAD

**Issue by fabianofernandes** [rictom/rede-cnpj#19]
Fiz o passo a passo que indicaste, mas estou com um erro na execução do rede cnpj
As imagens dos erros estão no link abaixo.
Estou instando em uma máquina local.

[https://1drv.ms/f/s!AsGroCl_KokkiN47zTY3PZnWe9zxOg?e=UTVCmG](url)
Também pareceu-me que está faltando uma parte no manual, entre o usar a base completa dos cnpjs.

**Comment by rictom** [comment]
Eu não consigo abrir a imagem. Acho que aqui no github, tem que colar uma imagem por vez... Se colar texto + imagem pode dar erro.

**Comment by fabianofernandes** [comment]
Somente copie e cole a url no navegador.

**Comment by rictom** [comment]
Vc está usando o Anaconda prompt? Vc acessa pelo menu de programas:
![image](https://github.com/rictom/rede-cnpj/assets/71139693/cf29e42d-69fa-4cea-8cdb-f2d5ad3d8e0c)

**Comment by fabianofernandes** [comment]
Usei, mas mesmo assim dá o mesmo erro.
Type error: the view function for server_rede_json_cnpj did not return a valid response

**Comment by rictom** [comment]
copia aqui, em formato texto mesmo, todo o console, desde o comando python rede.py que você deu

**Comment by rictom** [comment]
Tem esse erro:
ERROR : no such table: dlink.link_ete

Esse não é um nome de uma tabela do projeto. Vc mexeu no arquivo rede.ini? Veja como estão as linhas de configuração de 
base_XX = ... que elas tem que apontar para arquivos que que existam (no padrão, apontam para arquivos na pasta onde está o rede.py)

**Comment by fabianofernandes** [comment]
[BASE]
# base_rede é a tabela principal com os vínculos entre empresas e socios. Versão 0.9
base_rede = rede.db
#nome do arquivo ou caminho para a base sqlite de cnpj
base_receita = cnpj.db

#caminho da base de endereços normalizada
base_endereco_normalizado = cnpj_links_ete.db
#caminho da base de ligações adicional (TSE e TCE)
base_links =
#base_local é uma base com dados adicional. estrutura do banco_dados_modelo.db. Pode armazenar informações adicionadas manualmente no gráfico, dados dos nós e de ligações
base_local =
#referencia_bd aparece na linha superior da tela
referencia_bd = BASE DE TESTES
#pasta para armazenar arquivos json
pasta_arquivos=arquivos
porta_flask=5000

[INICIO]
#exibir mensagem de advertencia e informações da data de referencia
exibe_mensagem_advertencia = 1
mensagem_advertencia=LEIA ANTES DE PROSSEGUIR.\n\nTodos os dados exibidos são públicos, provenientes da página de dados públicos da Secretaria da Receita Federal.\nO autor não se responsibiliza pela utilização desses dados, pelo mau uso das informações ou incorreções.\n
#mensagem_advertencia=A base sqlite de TESTE tem empresas de pessoas politicamente expostas, conforme dados do Portal da Transparência da CGU.\nPara inserir um novo elemento digite TESTE ou nome do político.
#abrir menu inserir na abertura da tela
exibe_menu_inserir = 1

[ETC]
#para evitar excesso de ligações, se ligacaoSocioFilial=0 não inclue ligações para filiais de empresas
ligacao_socio_filial = 0

#permite download da pasta arquivos que não sejam json. Por segurança, desativar no servidor.
arquivos_download = 0
# parametros para o flask-limiter
limiter_padrao = 2/second;50/minute
limiter_dados = 2/second;50/minute;200/hour;400/day
limiter_google = 5/minute;50/hour;100/day
#permite busca do google
busca_google = 1
#baixa arquivos e consulta palavras chaves
busca_chaves = 1
#quantidade máxima de itens para geocode
geocode_max = 15
#para de acrescentar niveis se ultrapassar o tempo abaixo em segundos
tempo_maximo_consulta=10
#para de acrescentar niveis se ultrapassar a quantidade de itens abaixo
limite_registros_camada=1000

#.
#.

**Comment by rictom** [comment]
A sua pasta rede tem um arquivo cnpj_links_ete.db? Vc chegou a faze o procedimento para gerar este arquivo?
Pelo erro, acho que a rotina está procurando o arquivo cnpj_links_ete.db e não está encontrando.

**Comment by fabianofernandes** [comment]
Oi Amigo!
Realmente faltava essa base, veja o que deu de erro:
C:\rede-cnpj-master\rede\cnpj_normaliza_enderecos.py:323: RemovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  numeroDeRegistros = conBaseCompleta.execute('select count(*) from estabelecimento').fetchall()[0][0]
0 Tue May 23 16:24:15 2023
1000000 Tue May 23 16:33:50 2023
2000000 Tue May 23 16:39:17 2023
3000000 Tue May 23 16:44:35 2023
4000000 Tue May 23 16:50:48 2023
5000000 Tue May 23 16:56:32 2023
6000000 Tue May 23 17:02:29 2023
7000000 Tue May 23 17:08:57 2023
8000000 Tue May 23 17:16:05 2023
9000000 Tue May 23 17:23:23 2023
10000000 Tue May 23 17:31:24 2023
11000000 Tue May 23 17:38:43 2023
12000000 Tue May 23 17:46:29 2023
13000000 Tue May 23 17:54:05 2023
14000000 Tue May 23 18:01:40 2023
15000000 Tue May 23 18:09:55 2023
16000000 Tue May 23 18:18:30 2023
17000000 Tue May 23 18:26:48 2023
18000000 Tue May 23 18:35:26 2023
19000000 Tue May 23 18:44:02 2023
20000000 Tue May 23 18:52:49 2023
21000000 Tue May 23 19:02:30 2023
22000000 Tue May 23 19:11:28 2023
23000000 Tue May 23 19:20:49 2023
24000000 Tue May 23 19:30:03 2023
25000000 Tue May 23 19:39:38 2023
26000000 Tue May 23 19:49:09 2023
27000000 Tue May 23 19:59:34 2023
28000000 Tue May 23 20:09:09 2023
29000000 Tue May 23 20:19:27 2023
30000000 Tue May 23 20:29:26 2023
31000000 Tue May 23 20:39:45 2023
32000000 Tue May 23 20:50:38 2023
33000000 Tue May 23 21:01:33 2023
34000000 Tue May 23 21:12:00 2023
35000000 Tue May 23 21:22:31 2023
36000000 Tue May 23 21:33:12 2023
37000000 Tue May 23 21:43:55 2023
38000000 Tue May 23 21:55:48 2023
39000000 Tue May 23 22:06:34 2023
40000000 Tue May 23 22:17:54 2023
41000000 Tue May 23 22:28:58 2023
42000000 Tue May 23 22:40:22 2023
43000000 Tue May 23 22:51:54 2023
44000000 Tue May 23 23:04:16 2023
45000000 Tue May 23 23:15:55 2023
46000000 Tue May 23 23:28:04 2023
47000000 Tue May 23 23:39:54 2023
48000000 Tue May 23 23:51:42 2023
Traceback (most recent call last):
  File "C:\Users\Administrador\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\base.py", line 1880, in _execute_context
    self.dialect.do_executemany(
  File "C:\Users\Administrador\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 733, in do_executemany
    cursor.executemany(statement, parameters)
sqlite3.OperationalError: database or disk is full

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\rede-cnpj-master\rede\cnpj_normaliza_enderecos.py", line 621, in <module>
    baixa_enderecos_cnpj(False)
  File "C:\rede-cnpj-master\rede\cnpj_normaliza_enderecos.py", line 334, in baixa_enderecos_cnpj
    dftmptable.to_sql('endereco', conEnderecoNormalizado, if_exists='append', dtype=sqlalchemy.types.String)
  File "C:\ProgramData\anaconda3\lib\site-packages\pandas\core\generic.py", line 2987, in to_sql
    return sql.to_sql(
  File "C:\ProgramData\anaconda3\lib\site-packages\pandas\io\sql.py", line 695, in to_sql
    return pandas_sql.to_sql(
  File "C:\ProgramData\anaconda3\lib\site-packages\pandas\io\sql.py", line 1738, in to_sql
    total_inserted = sql_engine.insert_records(
  File "C:\ProgramData\anaconda3\lib\site-packages\pandas\io\sql.py", line 1335, in insert_records
    raise err
  File "C:\ProgramData\anaconda3\lib\site-packages\pandas\io\sql.py", line 1325, in insert_records
    return table.insert(chunksize=chunksize, method=method)
  File "C:\ProgramData\anaconda3\lib\site-packages\pandas\io\sql.py", line 946, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
  File "C:\ProgramData\anaconda3\lib\site-packages\pandas\io\sql.py", line 853, in _execute_insert
    result = conn.execute(self.table.insert(), data)
  File "C:\Users\Administrador\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\base.py", line 1380, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "C:\Users\Administrador\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\sql\elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\Administrador\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\Administrador\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\Administrador\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "C:\Users\Administrador\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\util\compat.py", line 211, in raise_
    raise exception
  File "C:\Users\Administrador\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\base.py", line 1880, in _execute_context
    self.dialect.do_executemany(
  File "C:\Users\Administrador\AppData\Roaming\Python\Python310\site-packages\sqlalchemy\engine\default.py", line 733, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database or disk is full
[SQL: INSERT INTO endereco ("index", cnpj, endereco, situacao) VALUES (?, ?, ?, ?)]
[parameters: ((0, '05977578000116', 'A ADERUP LOTE QUADRA 387 10 20-GOIANIA-GO', '04'), (1, '04310963000142', 'GOIAS SEDE 206-APORE-GO', '08'), (2, '22873772000251', 'MEXICO 2170-PORTO VELHO-RO', '08'), (3, '05977573000193', 'JOSE SAO 4-SAO LUIS-MA', '08'), (4, '00960941000177', 'ANTONIO EVERDOSA 1320-BELEM-PA', '08'), (5, '00960944000100', 'CUIBA 2473-SANTAREM-PA', '08'), (7, '02588518000113', 'CARMO N S 3-NAZARENO-MG', '08'), (9, '05977592000110', 'A JAPOARA LOJA 64-RIO DE JANEIRO-RJ', '04')  ... displaying 10 of 901228 total bound parameter sets ...  (999998, '03496541000140', 'A DANTAS SALA SENADOR 20 604 607-RIO DE JANEIRO-RJ', '08'), (999999, '05154742000195', 'BEIRA FRENTE MAR 1409-CUBATAO-SP', '08'))]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
l

**Comment by fabianofernandes** [comment]
Encontrei o erro. Disco cheio

**Comment by rictom** [comment]
Fechando o tópico, acho que já deve ter sido resolvido.
