### ISSUE TITLE
Sugestões de export JSON-LD e de simplificação

### ISSUE THREAD

**Issue by ppKrauss** [rictom/rede-cnpj#2]
Parece muito boa a proposta! O [filme](https://www.youtube.com/watch?v=nxz9Drhqn_I) mostra o potencial, infelizmente não terei tempo de testar... Pelo filme e breve análise ficam as sugestões:

1. ofertar não apenas a visualização mas também o dado ligado relativo à visualização. Idealmente JSON-LD com [Organization](https://schema.org/Organization) e [Person](https://schema.org/Person). Ambos CNPJ e CPF são [vatID](https://schema.org/vatID), ambos possuem [name](https://schema.org/name), etc. assim como especificidades, por exemplo a razão social é [legalName](https://schema.org/legalName).

2. Ilustrar caso simples, ou seja, "menos poluídos". Pode não ser trivial a estatística de principais diretores e/ou pessoas físicas que aparecem com maior número de vínculos num determinado cluster de pessoas jurídicas.

**Comment by rictom** [comment]
Obrigado pela sugestão, não conhecia esse conceito de JSON-LD, vou estudar. Coloquei uma versão funcionando online em [http://rtomi.pythonanywhere.com/rede/](http://rtomi.pythonanywhere.com/rede/).

**Comment by ppKrauss** [comment]
Boa ideia a funcionalidade online (!). Testei pelo WHOIS (fica outra sugestão pois na Internet mais do que Razão social e nome Fantasia o que lembramos são os domínios), por exemplo `uol.com.br` é 01.109.184/0004-38 ... Mas  a tela fica em branco.

**Comment by rictom** [comment]
A versão no pythonanywhere está usando uma base com cnpjs fictícios. Pelo link http://168.138.150.250/rede/ dá pra consultar a base completa pública com os dados de CNPJ.
