### ISSUE TITLE
Travando na parte final do script de tabelas

### ISSUE THREAD

**Issue by henriquearake1** [rictom/rede-cnpj#24]
Esse é o errro:

------------------------------
Tue Jul 25 17:55:42 2023 -executando parte: 3/4

insert into id_search
--select distinct id_descricao
select id_descricao
from (
select 'PJ_' || te.cnpj ||'-' || t.razao_social  as id_descricao
from cnpj.estabelecimento te
left join cnpj.empresas t on t.cnpj_basico=te.cnpj_basico
where te.matriz_filial is '1'
UNION ALL
select 'PJ_' || te.cnpj ||'-' || te.nome_fantasia  as id_descricao
from cnpj.estabelecimento te
-- where trim(te.nome_fantasia) <>'' --incluir este where faz que ignore cnpj filial sem nome fantasia, o que faz falta na hora de busca filiais por cnpj básico
UNION ALL
select  id1  as id_descricao
from rede.ligacao
where substr(id1,1,3)<>'PJ_'
UNION ALL
select  id2 as id_descricao
from  rede.ligacao
where substr(id2,1,3)<>'PJ_'
) as tunion
group by id_descricao --talvez group by seja mais rápido que distinct

Traceback (most recent call last):
  File "D:\rede-cnpj-master - julho\rede-cnpj-master\rede\bases\rede_cria_tabela_rede.db.py", line 246, in <module>
    executaSequencia(camDBrede_search, sqlsequencia=sql_search)
  File "D:\rede-cnpj-master - julho\rede-cnpj-master\rede\bases\rede_cria_tabela_rede.db.py", line 163, in executaSequencia
    engine.execute(sql)
sqlite3.OperationalError: disk I/O error

Esse erro ocorreu depois de algumas horas travado nessa etapa. Estou rodando novamente para ver se ocorre de novo.

**Comment by rictom** [comment]
Essa tabela rede_search.db é bem grande, vai ocupar uns 11GB no disco. Então você tem que ver se tem espaço suficiente, ao menos o dobro disso no HD. A mensagem também pode ser um problema de memória RAM, então se vc rodar de novo, abra o Gerenciador de Tarefas e veja quanto memória o processo está ocupando. Se chegar perto dos 100% é sinal que pode travar de novo. Se o seu micro tem pouca memória, feche os outros aplicativos.

**Comment by henriquearake1** [comment]
Espaço de HD tem tranquilo. Estou rodando em HD externo com um tera de espaço. Vou mandar o print aqui do gerenciador de tarefas. 
![image](https://github.com/rictom/rede-cnpj/assets/67759399/83e05e57-38d4-41a1-8f34-52a5696bf279)

Está parado no mesmo ponto há uma hora:

![image](https://github.com/rictom/rede-cnpj/assets/67759399/0e703986-92ae-4a6c-97d0-b83a53fbbe9b)

**Comment by rictom** [comment]
Pela imagem que vc mandou do gerenciador de tarefas, parece que o script não está rodando... Vc poderia ordenar por CPU e ver quanto consome algum processo Python. Estranho não aparecer na imagem. Para mim consome pelo menos uns 10 a 20% da cpu.
Uma coisa possível é vc ter clicado ou apertado alguma tecla com o console em primeiro plano e daí ter parado, devido à opção Modo de Edição Rápida do prompt. O python para mas fica difícil saber que isso aconteceu

**Comment by henriquearake1** [comment]
Eu sempre baixo o código fonte de novo tanto do rede quanto do cnpj toda vez que vou atualizar o banco de dados. Vou tentar rodar o script na versão anterior pra ver se ele vai travar no mesmo lugar

**Comment by rictom** [comment]
Olha, se já gerou o rede.db, você poderia economizar tempo e rodar só essa parte que gera o arquivo rede_search.db.  Se você entende de python, seria só recortar a parte que gera o rede.db... 
Ou você copia o sql e roda essa parte que gera o rede_search.db... Abre o Dbbrowser, cria um novo banco rede_search.db (não vai dar aproveitar esse), anexa o cnpj.db e rede.db e roda o sql.

**Comment by henriquearake1** [comment]
Eu cancelei o script. O arquivo rede que ele gerou dessa vez tem 4.5 Gb. Não deve estar completo. 

E eu não manjo quase nada de Python, não. sou advogado hahahaha

**Comment by rictom** [comment]
Entendi. Olha, se for rodar de novo, outra opção é tentar o programa baixar-converter.v2 que está em https://www.redecnpj.com.br/rede/aviso, que é mais simples. Só prestar atenção no começo, NÃO selecione as opções de baixar e de gerar o cnpj.db, escolha só a opção 3 de gerar o rede.db e rede_search.db.

**Comment by rictom** [comment]
E desativa o Modo de edição rápido, que acontece a coisa de parar a execução do nada

**Comment by henriquearake1** [comment]
Estou desconfiado que, na hora de gerar o cnpj.db, deve ter dado algum problema. De qualquer maneira, estuo rodando aqui a versão ".exe" pra ver se funciona. Retornarei.

**Comment by henriquearake1** [comment]
Atualizando, tentei rodar pelo baixar-converter.v2 e continua travando na hora de gerar o rede_search.db. Não estou conseguindo. Mesmo erro.

**Comment by rictom** [comment]
Quais os tamanhos dos arquivo cnpj.db e rede,db?

**Comment by henriquearake1** [comment]
Estou rodando o script novamente, mas o cnpj.db tem 30 gigas e o rede.db tinha 4 gigas, mas eu apaguei para rodar de novo para gerar o rede.db e o rede.search, que só tinha 25kb. Meu note tem 8gb de RAM e eu já tinha conseguido gerar esses arquivos usando o script (não o .exe) no mês passado.

**Comment by henriquearake1** [comment]
Chegamos na mesma parte e não há atividade no script.
![image](https://github.com/rictom/rede-cnpj/assets/67759399/b4837f97-13b6-48d2-b55f-fc0483672bd5)
![image](https://github.com/rictom/rede-cnpj/assets/67759399/dbaa60f0-04cc-4e52-8887-a538649d7fb3)
CNPJ.db com 30 gigas
rede.db com 4.5 gigas
rede_search 24kb

**Comment by rictom** [comment]
Como vc tentou várias vezes, provavelmente não vai funcionar. Talvez seja uma questão de memória RAM. Teria que tentar de forma diferente. Eu sugiro vc fazer a sugestão:
Abre o Dbbrowser (https://sqlitebrowser.org/), cria um novo banco rede_search.db,, anexa o cnpj.db e rede.db (botão anexar banco de dados). Numa aba Executar SQL vc roda:

DROP TABLE if exists id_search;
CREATE virtual TABLE id_search using fts5 (id_descricao);

insert into id_search
select 'PJ_' || te.cnpj ||'-' || t.razao_social  as id_descricao
from cnpj.estabelecimento te 
left join cnpj.empresas t on t.cnpj_basico=te.cnpj_basico
where te.matriz_filial is '1'
UNION ALL
select 'PJ_' || te.cnpj ||'-' || te.nome_fantasia  as id_descricao 
from cnpj.estabelecimento te 
-- where trim(te.nome_fantasia) <>'' --incluir este where faz que ignore cnpj filial sem nome fantasia, o que faz falta na hora de busca filiais por cnpj básico
UNION ALL
select  id1  as id_descricao
from rede.ligacao
where substr(id1,1,3)<>'PJ_'
UNION ALL
select  id2 as id_descricao
from  rede.ligacao
where substr(id2,1,3)<>'PJ_'

;

Isso deve levar pelo menos uma hora... Se o seu disco D for lento, talvez duas horas ou mais.

**Comment by rictom** [comment]
Se funcionar... tem que apertar o botão "Escrever modificações" para salvar senão vc perde tudo.

**Comment by henriquearake1** [comment]
Acho que está rodando:
![image](https://github.com/rictom/rede-cnpj/assets/67759399/c9a94214-98d3-4a69-88a4-8ba5f87999b4)
![image](https://github.com/rictom/rede-cnpj/assets/67759399/2ed30f01-3e62-4e2c-b81e-691dc19648a3)

**Comment by henriquearake1** [comment]
Acho que deu erro.
Não saiu do lugar
Interrompi aqui:

Execução finalizada com erros.
Resultado: interrupted
Na linha 4:
insert into id_search
select 'PJ_' || te.cnpj ||'-' || t.razao_social as id_descricao
from cnpj.estabelecimento te
left join cnpj.empresas t on t.cnpj_basico=te.cnpj_basico
where te.matriz_filial is '1'
UNION ALL
select 'PJ_' || te.cnpj ||'-' || te.nome_fantasia as id_descricao
from cnpj.estabelecimento te
-- where trim(te.nome_fantasia) <>'' --incluir este where faz que ignore cnpj filial sem nome fantasia, o que faz falta na hora de busca filiais por cnpj básico
UNION ALL
select id1 as id_descricao
from rede.ligacao
where substr(id1,1,3)<>'PJ_'
UNION ALL
select id2 as id_descricao
from rede.ligacao
where substr(id2,1,3)<>'PJ_'

;

**Comment by rictom** [comment]
Se você tiver paciência, roda esta sql...
Vc roda cada parte insert... até ; um por vez, pra ver se ele aceita.
Se você quiser uma outra solução, me manda um email para redecnpj.com.br@gmail.com


DROP TABLE if exists id_search;
CREATE virtual TABLE id_search using fts5 (id_descricao);

insert into id_search
select 'PJ_' || te.cnpj ||'-' || t.razao_social as id_descricao
from cnpj.estabelecimento te
left join cnpj.empresas t on t.cnpj_basico=te.cnpj_basico
where te.matriz_filial is '1'
;
insert into id_search
select 'PJ_' || te.cnpj ||'-' || te.nome_fantasia as id_descricao
from cnpj.estabelecimento te
-- where trim(te.nome_fantasia) <>'' --incluir este where faz que ignore cnpj filial sem nome fantasia, o que faz falta na hora de busca filiais por cnpj básico;
insert into id_search
select id1 as id_descricao
from rede.ligacao
where substr(id1,1,3)<>'PJ_'
;
insert into id_search
select id2 as id_descricao
from rede.ligacao
where substr(id2,1,3)<>'PJ_'

;

**Comment by henriquearake1** [comment]
Vou tentar agora

**Comment by henriquearake1** [comment]
É interessante, ele trava no primeiro insert. Vou te mandar e-mail.

**Comment by elielbarreto** [comment]
Tenho o mesmo problema, rodei os codigos que ele sugeriu para SQlite ai no final da conversa, e depois de 1 dia e 9 horas kkkk deu erro na linha 10. O arquivo rede_search.db ficou com 5.8gb aproximadamente

**Comment by elielbarreto** [comment]
Aqui é exatamente o mesmo erro que o seu henrique, na hora de criar rede_search.db ele fica na parte 3/4 e nao sai dali, eu esperei mais de 2 dias e nao passou a diante, seria melhor compactar o arquivo e disponibilizar para download pra a gente baixar, um computador médio fica impossível instalar isso
