### ISSUE TITLE
Problema na execução do script Instalação em ambiente linux 

### ISSUE THREAD

**Issue by bracalente** [rictom/rede-cnpj#26]
Eu baixei todos os arquivos do site da Receita, salvei na pasta correta do projeto dados-publicos-zip e ao rodar o script dados_cnpj_baixa.py com o python 3.9.2 estou vendo a mensagem de erro abaixo.

![image](https://github.com/rictom/rede-cnpj/assets/84627451/d834d861-b99f-49c4-8169-11154fb26d5e)

Alguem pode me ajudar, por favor?

Desde já, muito obrigado.

**Comment by bracalente** [comment]
informação sobre o erro na linha 194

![image](https://github.com/rictom/rede-cnpj/assets/84627451/6cccedf3-785f-4b0d-b9f0-a631201a5df9)

**Comment by rictom** [comment]
Vc ainda tem todo o texto do console? a partir de python dados_cnpj_baixa.py?

**Comment by bracalente** [comment]
└──╼ #python3 dados_cnpj_para_sqlite.py 
Início: Fri Sep 29 20:38:19 2023
Fri Sep 29 20:38:19 2023 descompactando dados-publicos-zip/Cnaes.zip
Fri Sep 29 20:38:19 2023 descompactando dados-publicos-zip/Empresas0.zip
Fri Sep 29 20:38:29 2023 descompactando dados-publicos-zip/Empresas1.zip
Fri Sep 29 20:38:34 2023 descompactando dados-publicos-zip/Empresas2.zip
Fri Sep 29 20:38:36 2023 descompactando dados-publicos-zip/Empresas3.zip
Fri Sep 29 20:38:40 2023 descompactando dados-publicos-zip/Empresas4.zip
Fri Sep 29 20:38:45 2023 descompactando dados-publicos-zip/Empresas5.zip
Fri Sep 29 20:38:50 2023 descompactando dados-publicos-zip/Empresas6.zip
Fri Sep 29 20:38:53 2023 descompactando dados-publicos-zip/Empresas7.zip
Fri Sep 29 20:38:58 2023 descompactando dados-publicos-zip/Empresas8.zip
Fri Sep 29 20:39:03 2023 descompactando dados-publicos-zip/Empresas9.zip
Fri Sep 29 20:39:05 2023 descompactando dados-publicos-zip/Estabelecimentos0.zip
Fri Sep 29 20:39:55 2023 descompactando dados-publicos-zip/Estabelecimentos1.zip
Fri Sep 29 20:40:08 2023 descompactando dados-publicos-zip/Estabelecimentos2.zip
Fri Sep 29 20:40:22 2023 descompactando dados-publicos-zip/Estabelecimentos3.zip
Fri Sep 29 20:40:39 2023 descompactando dados-publicos-zip/Estabelecimentos4.zip
Fri Sep 29 20:40:56 2023 descompactando dados-publicos-zip/Estabelecimentos5.zip
Fri Sep 29 20:41:13 2023 descompactando dados-publicos-zip/Estabelecimentos6.zip
Fri Sep 29 20:41:26 2023 descompactando dados-publicos-zip/Estabelecimentos7.zip
Fri Sep 29 20:41:39 2023 descompactando dados-publicos-zip/Estabelecimentos8.zip
Fri Sep 29 20:41:56 2023 descompactando dados-publicos-zip/Estabelecimentos9.zip
Fri Sep 29 20:42:13 2023 descompactando dados-publicos-zip/Motivos.zip
Fri Sep 29 20:42:13 2023 descompactando dados-publicos-zip/Municipios.zip
Fri Sep 29 20:42:13 2023 descompactando dados-publicos-zip/Naturezas.zip
Fri Sep 29 20:42:13 2023 descompactando dados-publicos-zip/Paises.zip
Fri Sep 29 20:42:13 2023 descompactando dados-publicos-zip/Qualificacoes.zip
Fri Sep 29 20:42:13 2023 descompactando dados-publicos-zip/Simples.zip
Fri Sep 29 20:42:33 2023 descompactando dados-publicos-zip/Socios0.zip
Fri Sep 29 20:42:38 2023 descompactando dados-publicos-zip/Socios1.zip
Fri Sep 29 20:42:40 2023 descompactando dados-publicos-zip/Socios2.zip
Fri Sep 29 20:42:42 2023 descompactando dados-publicos-zip/Socios3.zip
Fri Sep 29 20:42:43 2023 descompactando dados-publicos-zip/Socios4.zip
Fri Sep 29 20:42:46 2023 descompactando dados-publicos-zip/Socios5.zip
Fri Sep 29 20:42:48 2023 descompactando dados-publicos-zip/Socios6.zip
Fri Sep 29 20:42:50 2023 descompactando dados-publicos-zip/Socios7.zip
Fri Sep 29 20:42:52 2023 descompactando dados-publicos-zip/Socios8.zip
Fri Sep 29 20:42:54 2023 descompactando dados-publicos-zip/Socios9.zip
carregando tabela dados-publicos/F.K03200$Z.D30909.CNAECSV
/home/parrot/Desktop/rede/cnpj-sqlite/dados_cnpj_para_sqlite.py:48: RemovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  engine.execute(f'CREATE INDEX idx_{nomeTabela} ON {nomeTabela}(codigo);')
carregando tabela dados-publicos/F.K03200$Z.D30909.MOTICSV
carregando tabela dados-publicos/F.K03200$Z.D30909.MUNICCSV
carregando tabela dados-publicos/F.K03200$Z.D30909.NATJUCSV
carregando tabela dados-publicos/F.K03200$Z.D30909.PAISCSV
carregando tabela dados-publicos/F.K03200$Z.D30909.QUALSCSV
carregando: arq='dados-publicos/K3241.K03200Y0.D30909.EMPRECSV'
lendo csv ... Fri Sep 29 20:43:03 2023
fim parcial... Fri Sep 29 20:45:59 2023
carregando: arq='dados-publicos/K3241.K03200Y1.D30909.EMPRECSV'
lendo csv ... Fri Sep 29 20:45:59 2023
fim parcial... Fri Sep 29 20:46:51 2023
carregando: arq='dados-publicos/K3241.K03200Y2.D30909.EMPRECSV'
lendo csv ... Fri Sep 29 20:46:51 2023
fim parcial... Fri Sep 29 20:47:45 2023
carregando: arq='dados-publicos/K3241.K03200Y3.D30909.EMPRECSV'
lendo csv ... Fri Sep 29 20:47:45 2023
fim parcial... Fri Sep 29 20:48:49 2023
carregando: arq='dados-publicos/K3241.K03200Y4.D30909.EMPRECSV'
lendo csv ... Fri Sep 29 20:48:49 2023
fim parcial... Fri Sep 29 20:49:58 2023
carregando: arq='dados-publicos/K3241.K03200Y5.D30909.EMPRECSV'
lendo csv ... Fri Sep 29 20:49:58 2023
fim parcial... Fri Sep 29 20:50:55 2023
carregando: arq='dados-publicos/K3241.K03200Y6.D30909.EMPRECSV'
lendo csv ... Fri Sep 29 20:50:55 2023
fim parcial... Fri Sep 29 20:52:02 2023
carregando: arq='dados-publicos/K3241.K03200Y7.D30909.EMPRECSV'
lendo csv ... Fri Sep 29 20:52:02 2023
fim parcial... Fri Sep 29 20:53:07 2023
carregando: arq='dados-publicos/K3241.K03200Y8.D30909.EMPRECSV'
lendo csv ... Fri Sep 29 20:53:07 2023
fim parcial... Fri Sep 29 20:54:12 2023
carregando: arq='dados-publicos/K3241.K03200Y9.D30909.EMPRECSV'
lendo csv ... Fri Sep 29 20:54:12 2023
fim parcial... Fri Sep 29 20:55:07 2023
carregando: arq='dados-publicos/K3241.K03200Y0.D30909.ESTABELE'
lendo csv ... Fri Sep 29 20:55:07 2023
fim parcial... Fri Sep 29 21:04:52 2023
carregando: arq='dados-publicos/K3241.K03200Y1.D30909.ESTABELE'
lendo csv ... Fri Sep 29 21:04:52 2023
fim parcial... Fri Sep 29 21:07:42 2023
carregando: arq='dados-publicos/K3241.K03200Y2.D30909.ESTABELE'
lendo csv ... Fri Sep 29 21:07:42 2023
fim parcial... Fri Sep 29 21:10:33 2023
carregando: arq='dados-publicos/K3241.K03200Y3.D30909.ESTABELE'
lendo csv ... Fri Sep 29 21:10:33 2023
fim parcial... Fri Sep 29 21:13:19 2023
carregando: arq='dados-publicos/K3241.K03200Y4.D30909.ESTABELE'
lendo csv ... Fri Sep 29 21:13:19 2023
fim parcial... Fri Sep 29 21:16:23 2023
carregando: arq='dados-publicos/K3241.K03200Y5.D30909.ESTABELE'
lendo csv ... Fri Sep 29 21:16:23 2023
fim parcial... Fri Sep 29 21:19:22 2023
carregando: arq='dados-publicos/K3241.K03200Y6.D30909.ESTABELE'
lendo csv ... Fri Sep 29 21:19:22 2023
fim parcial... Fri Sep 29 21:22:08 2023
carregando: arq='dados-publicos/K3241.K03200Y7.D30909.ESTABELE'
lendo csv ... Fri Sep 29 21:22:08 2023
fim parcial... Fri Sep 29 21:24:55 2023
carregando: arq='dados-publicos/K3241.K03200Y8.D30909.ESTABELE'
lendo csv ... Fri Sep 29 21:24:55 2023
fim parcial... Fri Sep 29 21:27:47 2023
carregando: arq='dados-publicos/K3241.K03200Y9.D30909.ESTABELE'
lendo csv ... Fri Sep 29 21:27:47 2023
fim parcial... Fri Sep 29 21:30:39 2023
carregando: arq='dados-publicos/K3241.K03200Y0.D30909.SOCIOCSV'
lendo csv ... Fri Sep 29 21:30:39 2023
fim parcial... Fri Sep 29 21:31:53 2023
carregando: arq='dados-publicos/K3241.K03200Y1.D30909.SOCIOCSV'
lendo csv ... Fri Sep 29 21:31:53 2023
fim parcial... Fri Sep 29 21:32:29 2023
carregando: arq='dados-publicos/K3241.K03200Y2.D30909.SOCIOCSV'
lendo csv ... Fri Sep 29 21:32:29 2023
fim parcial... Fri Sep 29 21:32:59 2023
carregando: arq='dados-publicos/K3241.K03200Y3.D30909.SOCIOCSV'
lendo csv ... Fri Sep 29 21:32:59 2023
fim parcial... Fri Sep 29 21:33:30 2023
carregando: arq='dados-publicos/K3241.K03200Y4.D30909.SOCIOCSV'
lendo csv ... Fri Sep 29 21:33:30 2023
fim parcial... Fri Sep 29 21:34:00 2023
carregando: arq='dados-publicos/K3241.K03200Y5.D30909.SOCIOCSV'
lendo csv ... Fri Sep 29 21:34:00 2023
fim parcial... Fri Sep 29 21:34:28 2023
carregando: arq='dados-publicos/K3241.K03200Y6.D30909.SOCIOCSV'
lendo csv ... Fri Sep 29 21:34:28 2023
fim parcial... Fri Sep 29 21:35:01 2023
carregando: arq='dados-publicos/K3241.K03200Y7.D30909.SOCIOCSV'
lendo csv ... Fri Sep 29 21:35:01 2023
fim parcial... Fri Sep 29 21:35:30 2023
carregando: arq='dados-publicos/K3241.K03200Y8.D30909.SOCIOCSV'
lendo csv ... Fri Sep 29 21:35:30 2023
fim parcial... Fri Sep 29 21:35:58 2023
carregando: arq='dados-publicos/K3241.K03200Y9.D30909.SOCIOCSV'
lendo csv ... Fri Sep 29 21:35:58 2023
fim parcial... Fri Sep 29 21:36:27 2023
carregando: arq='dados-publicos/F.K03200$W.SIMPLES.CSV.D30909'
lendo csv ... Fri Sep 29 21:36:27 2023
Killed

**Comment by bracalente** [comment]
outro erro agora...

**Comment by rictom** [comment]
Vc está no linux, vc criou um novo ambiente virtual? Por exemplo, https://www.geeksforgeeks.org/creating-python-virtual-environment-windows-linux/
Isso é importante, porque vc separa o projeto das outras coisas que estão rodando no linux.
Já em um ambiente virtual, vc roda o pip -r requirements.txt do github do cnpj-sqlite. Isso é um passo importante porque a última versão do sqlalchemy dá algum problema com o pandas (ou outra biblioteca), então precisa de uma versão mais antiga do sqlalchemy

**Comment by rictom** [comment]
o correto é 
pip install -r requirements.txt

**Comment by bracalente** [comment]
Boa noite, o comando #python3 dados_cnpj_para_sqlite.py  foi concluido com sucesso, mas gerou apenas o arquivo cnpj.db
![image](https://github.com/rictom/rede-cnpj/assets/84627451/20f96b01-dba6-4bf0-8067-c3fda7f691ff)

**Comment by bracalente** [comment]
a pergunta é como gero os demais arquivos? muito obrigado!

**Comment by bracalente** [comment]
Rodou parcialmente, eu não consigo adicionar as camadas para ver por exemplo os socios da empresa.
![image](https://github.com/rictom/rede-cnpj/assets/84627451/1b01436f-4dc4-4f4f-8d0c-0b4fb4143df5)

**Comment by rictom** [comment]
Veja lá em https://github.com/rictom/rede-cnpj/blob/master/doc/instalacao_windows.md
que explica como gerar os arquivos rede.db e rede_search.db, que são necessários para ver as ligações.

**Comment by bracalente** [comment]
Boa noite, funcionando perfeitamente! Muito obrigado!

**Comment by bracalente** [comment]
Obrigado
