### ISSUE TITLE
Novo Layout de Dados

### ISSUE THREAD

**Issue by JamesonBR** [rictom/rede-cnpj#3]
Olá, pretende implementar esse novo modelo de dados no projeto?

https://www.gov.br/receitafederal/pt-br/assuntos/orientacao-tributaria/cadastros/consultas/arquivos/NOVOLAYOUTDOSDADOSABERTOSDOCNPJ.pdf

**Comment by rictom** [comment]
Sim, quando eu tiver tempo eu vou atualizar.

**Comment by rictom** [comment]
Atualizei o código para o layout novo de tabelas.
O repositório vem com uma base de testes para testar a rotina. 
A  base completa tem 5GB compactados que carreguei no [google drive ](https://drive.google.com/drive/folders/1Gkeq27aHv6UgT8m30fc4hZWMPqdhEHWr?usp=sharing), são 5 pedaços compactados usando 7zip.
Inclui umas colunas de cnpj a mais nas tabelas, para facilitar na hora de fazer as consultas do projeto. 
A base tem muitos erros na tabela de sócios, com nomes de empresas (que são sócias) incorretos. Nesses casos a rotina só pega a Razão Social da tabela empresas, que espero que esteja correta.

**Comment by Eduardomb22** [comment]
@rictom Prezado, boa tarde. Saiu uma nova atualização, depois nos dê o parecer se está tudo, aparentemente, correto.
