### ISSUE TITLE
Exibição do correio eletrônico/telefone/endereço

### ISSUE THREAD

**Issue by Edu-Vidal** [rictom/rede-cnpj#5]
Curti esta maneira de visualizar os dados da RF, ótimo trabalho!
Gostaria de fazer a visualização offline, mas, após implementar, não consegui replicar a exibição das ligações entre empresas e seus respectivos dados da maneira como está disponibilizado online atualmente. O que está faltando?

**Comment by rictom** [comment]
Obrigado por testar o projeto. Para visualizar as ligações de endereços, vc precisa baixar e descompactar o arquivo link_ete.db.7z que copiei agora no google drive em https://drive.google.com/drive/folders/1Gkeq27aHv6UgT8m30fc4hZWMPqdhEHWr
Com o arquivo descompactado, vc edita o arquivo rede.ini e coloca
base_endereco_normalizado = links_ete.db

**Comment by Edu-Vidal** [comment]
Ótimo, está funcionando aqui, muito obrigado!

**Comment by Esvj** [comment]
Olá Rictom. 
Pode disponibilizar o arquivo link_ete.db.7z?
