### ISSUE TITLE
Retorno de Telefone e Localização no Gráfico

### ISSUE THREAD

**Issue by JamesonBR** [rictom/rede-cnpj#7]
Olá, como habilitar para apresentar o telefone e o endereço no gráfico ao fazer a consulta do CNPJ?

como apresentado no demo online:

http://168.138.150.250/rede/

**Comment by rictom** [comment]
Para ativar as ligações de telefone e endereço, vc deve editar o arquivo rede.ini e alterar a linha
base_endereco_normalizado =links_ete.db

Em https://drive.google.com/drive/folders/1Gkeq27aHv6UgT8m30fc4hZWMPqdhEHWr tem o arquivo links_ete.db compactado para baixar.

**Comment by JamesonBR** [comment]
Bacana! Qual procedimento pra gerar esse banco de dados?

**Comment by rictom** [comment]
Eu fiz um script em python, que remove espaços dos endereços, troca abreviaturas, remove algumas expressões. Depois agrupa, mantém apenas os com repetição, cria a tabela de ligacao do cnpj para o endereço/telefone/email. O código está bagunçado, quando eu conseguir arrumar eu coloco.

Outra coisa que vc pode fazer é indexar para usar o busca por parte do nome ou razão social. Vc deve abrir o 
cnpj.db num programa como o HeidiSQL ou DB Browser for sqlite e rodar os comandos:

CREATE virtual TABLE empresas_search using fts5 (razao_social);
insert into empresas_search
Select razao_social
from empresas;

CREATE virtual TABLE socios_search using fts5 (nome_socio);
insert into socios_search
select nome_socio
from socios;

Depois, ajuste o arquivo rede.ini e coloque a linha
base_receita_fulltext = cnpj.db

**Comment by rictom** [comment]
ver comentário em https://github.com/rictom/rede-cnpj/issues/4
